name: Enforce Signed Commits

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
      - ready_for_review

permissions:
  checks: write
  contents: read

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  check_sign_status:
    name: Verify sign status of the pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Ensure all commits are signed
        run: |
          if git log --format='%G?' origin/main..HEAD | grep -v 'G'; then
            echo "ERROR: Found unsigned or unverified commits."
            exit 1
          fi
